### ISSUE TITLE
Error today building web3modal

### ISSUE THREAD

**Issue by topleft1562** [WalletConnect/walletconnect-utils#166] opened 2024-04-08 16:05 UTC
Getting a error pointing at the logger , when building my page using @web3modal/wagmi

**Comment by phemex-docs** [comment] 2024-04-08 16:29
The same problem occurs with @walletconnect/logger version  2.1.1

`Error [RollupError]: "Writable" is not exported by "__vite-browser-external", imported by "../../node_modules/.pnpm/...@walletconnect+logger@2.1.1/node_modules/@walletconnect/logger/dist/index.es.js".`

**Comment by topleft1562** [comment] 2024-04-08 16:35
Yes thats my error now. Will await a resolution.

**Comment by devceline** [comment] 2024-04-08 16:57
Duplicate of https://github.com/WalletConnect/walletconnect-monorepo/issues/4414 - Investigating.

**Comment by kunaljain0212** [comment] 2024-04-08 18:57
I am currently using web3modal in one of my projects and an hour back I removed my package-lock file and node_modules folder to do a fresh `npm i`. Post that the build started breaking. I wanted to ask, when I do `npm i` does it try installing the latest minor/patched version of the package because I have the carrot `^` symbol with the package version in my package.json file and so because of a breaking minor/patch release it started breaking? 

If yes, then should I remove `^` symbol from my packages to ensure this doesn't happen in future and it always installs the versions that are currently resulting in a safe build?

**Closed** 2024-04-08 19:16 UTC

**Comment by devceline** [comment] 2024-04-08 19:29
Fix for this currently in our release pipeline

**Comment by devceline** [comment] 2024-04-08 20:05
- This only affects packages dependent on `@walletconnect/logger@2.1.0` and `@walletconnect/logger/@2.1.1`. 
- Which in turn only affects `@walletconnect/core@2.12.0` and `@walletconnect/core@2.12.1`

So this only affects `@walletconnect/web3wallet@2.11.0` and `@walletconnect/web3wallet@2.11.1` 

Can you please indicate the version of `@web3modal/wagmi` you are using?

Regardless - the fix for this should be out tomorrow.

**Comment by topleft1562** [comment] 2024-04-08 20:34
Im having success already.  Something has been fixed for my repo. Thank you.

Using @web3modal/wagmi 4.1.5

**Comment by kunaljain0212** [comment] 2024-04-09 05:59
> * This only affects packages dependent on `@walletconnect/logger@2.1.0` and `@walletconnect/logger/@2.1.1`.
> * Which in turn only affects `@walletconnect/core@2.12.0` and `@walletconnect/core@2.12.1`
> 
> So this only affects `@walletconnect/web3wallet@2.11.0` and `@walletconnect/web3wallet@2.11.1`
> 
> Can you please indicate the version of `@web3modal/wagmi` you are using?
> 
> Regardless - the fix for this should be out tomorrow.

My version is `"@web3modal/wagmi": "^3.5.3",`
